faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index, name='index'),
    path('Add/', views.Add, name='Add'),
    path('Delete/<pk>/', views.Delete, name='Delete'),
    path('Edit/<int:idx>/', views.Edit, name='Edit'),

]

hoaxbuster/urls.py
from django.urls import path

from . import views

app_name = 'hoaxbuster'

urlpatterns = [
    path('', views.index, name='index'),
    path('addinfo', views.addinfo, name='addinfo'),
    path('deleteinfo/<int:info_id>', views.deleteinfo, name='deleteinfo'),
    path('updateinfo/<int:info_id>', views.updateinfo, name='updateinfo'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('faq/', include('faq.urls')),
    path('hoaxbuster/', include('hoaxbuster.urls')),
    path('penanganan/', include('penanganan.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoaxbuster/models.py
from django.db import models

# Create your models here.

class Info(models.Model):
    hoax = models.TextField()
    fakta = models.TextField()
    image = models.ImageField(default="default.png", blank=True)

hoaxbuster/forms.py
from django.forms import ModelForm
from .models import Info

class InfoForm(ModelForm):
    class Meta:
        model = Info
        fields = '__all__'

hoaxbuster/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

from .models import Info
from .forms import InfoForm

# Create your views here.

def index(request):
    infos = Info.objects.all()
    context = {'infos':infos}
    
    return render(request, 'hoaxbuster/index.html', context)

def updateinfo(request, info_id):
    info = Info.objects.get(id=info_id)
    form = InfoForm(instance=info)
    context = {'form':form}

    if request.method == 'POST': 
        form = InfoForm(request.POST, request.FILES, instance=info)
  
        if form.is_valid():
            form.save()
        
        return redirect('/hoaxbuster/')

    return render(request, 'hoaxbuster/updateinfo.html', context)

def addinfo(request):
    form = InfoForm()
    context = {'form':form}

    if request.method == 'POST': 
        form = InfoForm(request.POST, request.FILES)
  
        if form.is_valid():
            form.save()
        
        return redirect('/hoaxbuster/')

    return render(request, 'hoaxbuster/addinfo.html', context)

def deleteinfo(request, info_id):
    info = Info.objects.get(id=info_id)
    info.delete()

    return redirect('/hoaxbuster/')

hoaxbuster/templates/hoaxbuster/addinfo.html
{% extends 'form.html' %}

{% block title %}
Hoaxbuster - Add Info
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'hoaxbuster/style.css' %}">

{% endblock head %}

{% block styling %}
#id_hoax, #id_fakta {
    width: 350px;
    height: 100px;
}
{% endblock styling %}

{% block body %}

<div class="container">
    <div class="row blank"></div>
    <div class="row justify-content-center">
        <h1 class="title">Hoax Buster</h1>
    </div>

    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST" enctype="multipart/form-data">
            <table class="table form">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2" style="text-align: center;">
                            {% csrf_token %}
                            <input class="btn btn-info" type="submit" value="Add Info" style="padding-right: 50px; padding-left: 50px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>

</div>

{% endblock body %}

hoaxbuster/templates/hoaxbuster/index.html
{% extends 'template.html' %}

{% block title %}
Hoaxbuster
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'hoaxbuster/style.css' %}">

{% endblock head %}

{% block styling %}
{% endblock styling %}

{% block body %}

<div class="container">
    <div class="row blank"></div>
    <div class="row justify-content-center">
        <h1 class="title">Hoax Buster</h1>
    </div>

    {% if infos %}

    <div class="row justify-content-center">
        <table class="table table-hover info" style="width: 80%;">
            <thead>
                <tr>
                    <th scope="col" style="width: 150px;"></th>
                    <th scope="col" style="text-align: center;">Hoax</th>
                    <th scope="col" style="text-align: center;">Fakta</th>
                    <th scope="col" style="width: 150px;"></th>
                </tr>
            </thead>
            <tbody>
    
            {% for info in infos %}
    
                <tr>
                    <th scope="row">
                        <img src="{{ info.image.url }}" style="width: 150px; height: 150px; border-radius: 50%;">
                    </th>
                    <td style="text-align: center;">{{ info.hoax }}</td>
                    <td style="text-align: center;">{{ info.fakta }}</td>
                    <td>
                        <form action="/hoaxbuster/updateinfo/{{ info.id }}" method="GET" style="display: inline;">
                            {% csrf_token %}
                            <input class="btn btn-success" type="submit" value="Update" style="width: 100%; margin: 2px;">
                        </form>
                        <br>
                        <form action="/hoaxbuster/deleteinfo/{{ info.id }}" method="POST" style="display: inline;">
                            {% csrf_token %}
                            <input class="btn btn-danger" type="submit" value="Delete" style="width: 100%; margin: 2px;">
                        </form>
                    </td>
                </tr>
    
            {% endfor %}
    
            </tbody>
        </table>
    </div>

    {% endif %}
    
    <div class="row justify-content-center">
        <a class="btn btn-info" style="padding-left: 50px; padding-right: 50px;" href= "{% url 'hoaxbuster:addinfo' %}">Add Info</a>
    </div>
    <div class="row blank"></div>

</div>

{% endblock body %}

hoaxbuster/templates/hoaxbuster/updateinfo.html
{% extends 'form.html' %}

{% block title %}
Hoaxbuster - Update Info
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'hoaxbuster/style.css' %}">

{% endblock head %}

{% block styling %}
#id_hoax, #id_fakta {
    width: 350px;
    height: 100px;
}
{% endblock styling %}

{% block body %}

<div class="container">
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h1 class="title">Hoax Buster</h1>
    </div>

    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST" enctype="multipart/form-data">
            <table class="table form">
                <tbody>
                    {% csrf_token %}
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2" style="text-align: center;">
                            <input class="btn btn-info" type="submit" value="Update Info" style="padding-right: 50px; padding-left: 50px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>

</div>

{% endblock body %}